### ISSUE TITLE
Ruby 3+ support

### ISSUE THREAD

**Issue by mhfs** [sunny/graph_attack#12]
Hey there, first of all, thanks for this library!

I just noticed that the gemspec is locked for Ruby < 2.8. Any plans on supporting more recent versions?

Thank you

**Comment by sunny** [comment]
Hi there! I don’t think there should be any issue with Ruby 3, so we can probably ease (or remove) the Ruby version lock.

**Comment by mhfs** [comment]
Thank you, you're so responsive ❤️ .

**Comment by mhfs** [comment]
@sunny could we get a release please? ;)

**Comment by atipugin** [comment]
Can't wait for release too :)

**Comment by sunny** [comment]
Released as 2.0.0! Thank you again for reporting the issue 🎉
