### ISSUE TITLE
Ruby 3.2+ support

### ISSUE THREAD

**Issue by diegodelvalle** [sunny/graph_attack#23]
Hi there, hope you are doing well!

I was wondering if there are any plans of supporting ruby 3.2+. I don't know if there are any incompatibilities.

Thanks in advance and keep up the good work!

**Comment by sunny** [comment]
Hi @diegodelvalle! I have added Ruby 3.2 to the automated test suite. No incompatibilites have popped up, so I’ve relaxed the version in #24 and pushed 2.3.1 🎉
