### ISSUE TITLE
Breaking Change from 2.1.0 to 2.2.0

### ISSUE THREAD

**Issue by thenovelnomad** [sunny/graph_attack#40]
This is more of an FYI, than a bug.

If `Redis.current =` is used to configure the redis client in your application, then upgrading from 2.1.0 to 2.2.0 will break the Graph Attack redis client, as it switched form using `Redis.current` to set the redis client to `Redis.new`.

2.1.0 GraphAttack::RateLimit#redis_client
```
def redis_client
  options[:redis_client] || Redis.current
end
```
https://github.com/sunny/graph_attack/blob/v2.1.0/lib/graph_attack/rate_limit.rb#L52

2.2.0 GraphAttack::RateLimit#redis_client
```
def redis_client
  options[:redis_client] || Redis.new
end
```
https://github.com/sunny/graph_attack/blob/v2.2.0/lib/graph_attack/rate_limit.rb#L51

**Comment by sunny** [comment]
Good call, the CHANGELOG doesn’t reflect that change! Sorry for that. I’ll add it retroactively with a warning.

The reasoning behind this change is that [`Redis.current` is deprecated](https://github.com/redis/redis-rb/commit/9745e22db65ac294be51ed393b584c0f8b72ae98) and will be removed in Redis 5.0.

**Comment by sunny** [comment]
Thank you for reporting this!
